<?php

$payment_items = [

    ["name"=>"Foreign basic Qualifications","payment_item_category_id"=>"2","fee"=>"600.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Local basic Qualifications","payment_item_category_id"=>"2","fee"=>"200.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Specialist Registration","payment_item_category_id"=>"2","fee"=>"400.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Student registrations(Ultra Sound) Burwin","payment_item_category_id"=>"2","fee"=>"200.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Student Registration (undergraduate)","payment_item_category_id"=>"2","fee"=>"15.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"X-ray/unit","payment_item_category_id"=>"3","fee"=>"3000.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Scan/unit","payment_item_category_id"=>"3","fee"=>"3000.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Psychologists","payment_item_category_id"=>"3","fee"=>"1500.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Ambulances/2 ambulances","payment_item_category_id"=>"3","fee"=>"3000.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Any other/unit","payment_item_category_id"=>"3","fee"=>"1500.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Air Ambulance Services","payment_item_category_id"=>"3","fee"=>"6000.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Change of premises","payment_item_category_id"=>"3","fee"=>"600.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Change of practitioner in charge","payment_item_category_id"=>"3","fee"=>"750.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Accreditation of Training Schools","payment_item_category_id"=>"3","fee"=>"3000.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Practising in an unregistered premises (public sector)","payment_item_category_id"=>"4","fee"=>"1000.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Practising in an unregistered premises (private sector)","payment_item_category_id"=>"4","fee"=>"1000.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Late renewal (second quarter)","payment_item_category_id"=>"4","fee"=>"150.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Late renewal (third quarter)","payment_item_category_id"=>"4","fee"=>"200.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Late renewal (fourth quarter)","payment_item_category_id"=>"4","fee"=>"250.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Local qualification","payment_item_category_id"=>"6","fee"=>"80.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Foreign based qualification","payment_item_category_id"=>"6","fee"=>"400.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Local practitioner","payment_item_category_id"=>"7","fee"=>"400.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Foreign based practitioner","payment_item_category_id"=>"7","fee"=>"800.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Provisional To Permanent Register","payment_item_category_id"=>"8","fee"=>"80.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Registration Certificates","payment_item_category_id"=>"9","fee"=>"200.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Practicing Certificate","payment_item_category_id"=>"9","fee"=>"80.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Reactivation fee","payment_item_category_id"=>"10","fee"=>"200.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Ultrasound Viva- Burwin","payment_item_category_id"=>"12","fee"=>"450.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Foreign Registrations","payment_item_category_id"=>"12","fee"=>"450.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Ultrasound Examinations","payment_item_category_id"=>"12","fee"=>"450.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Psychology Examinations","payment_item_category_id"=>"12","fee"=>"450.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Ultrasound �Burwin","payment_item_category_id"=>"11","fee"=>"450.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Renewal Balance","payment_item_category_id"=>"1","fee"=>"0.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"Registration Balance","payment_item_category_id"=>"2","fee"=>"0.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"ALTERATIONS ON REGISTERS","payment_item_category_id"=>"13","fee"=>"40.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"ASSESSMENT OF QUALIFICATION","payment_item_category_id"=>"13","fee"=>"80.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"OFFICIAL STAMP & CONFIRMATION","payment_item_category_id"=>"13","fee"=>"60.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"SALE OF REGISTER","payment_item_category_id"=>"13","fee"=>"40.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"SEARCH FOR RECORDS & RETRIVAL OF DOCUMENTS","payment_item_category_id"=>"13","fee"=>"80.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"APPEALS","payment_item_category_id"=>"5","fee"=>"600.00","created_at"=>now(),"updated_at"=>now()],
    ["name"=>"CPD BOOKLETS","payment_item_category_id"=>"13","fee"=>"8.00","created_at"=>now(),"updated_at"=>now()],

];
return $payment_items;